import { isAbsolute, join, relative, sep } from "node:path";
import {
  MARKERS,
  countManagedBlocks,
  removeManagedBlocks,
  stripMarkers,
} from "./managed-block.js";
import { readUtf8IfExists, writeIfChanged } from "./file-io.js";
import { renderSyncedSkillsBlock, type SkillSelection } from "./skills.js";
import type { McpServerDefinition } from "./mcp-renderers.js";
import type { HookMode } from "../tools/sources.js";

/**
 * The instruction files each tool reads — CLAUDE.md, AGENTS.md, GEMINI.md,
 * Cursor's rule file, Copilot's instructions — and the managed block xtctx
 * owns inside them.
 *
 * Which files, what goes in the block, and how it is inserted are one subject:
 * every one of them is about a file whose other contents belong to the user.
 * `managed-block.ts` underneath handles marker mechanics on a string; this is
 * the layer that knows which files those strings live in.
 */

export interface MemoryTarget {
  tool: string;
  path: string;
  hookMode: HookMode;
  prelude?: string;
}

export function memoryTargets(projectRoot: string): MemoryTarget[] {
  return [
    {
      tool: "codex",
      path: join(projectRoot, "AGENTS.md"),
      hookMode: "instruction-only",
    },
    {
      tool: "claude-code",
      path: join(projectRoot, "CLAUDE.md"),
      hookMode: "executable",
    },
    {
      tool: "antigravity",
      path: join(projectRoot, "GEMINI.md"),
      hookMode: "instruction-only",
    },
    {
      tool: "cursor",
      path: join(projectRoot, ".cursor", "rules", "xtctx.mdc"),
      hookMode: "instruction-only",
      prelude:
        "---\ndescription: xtctx cross-tool handoff\nglobs: \"**/*\"\nalwaysApply: true\n---\n\n",
    },
    {
      tool: "copilot",
      path: join(projectRoot, ".github", "copilot-instructions.md"),
      hookMode: "instruction-only",
    },
  ];
}

/**
 * Rewrite a path inside the project root to a `./`-relative one, and pass
 * anything else through unchanged (`-y`, `xtctx`, a path outside the project).
 * Used only for text that gets committed; see the call site.
 */
function portablePath(arg: string, projectRoot: string): string {
  // Absolute first, and it is not a shortcut. Every path this needs to rewrite
  // is built with `join(projectRoot, …)`, so anything relative is a flag or a
  // package name. Without this test `relative()` resolves a bare `-y` against
  // the *process cwd*, and `cd project && npx -y xtctx setup` — the documented
  // way to run it — made the cwd the project root and turned the flag into
  // `./-y`. The block then advertised `npx ./-y ./xtctx`, a command that does
  // not exist, and its contents depended on which directory setup was run
  // from, so re-running churned a committed file.
  if (!isAbsolute(arg)) {
    return arg;
  }

  const rel = relative(projectRoot, arg);
  if (!rel || rel.startsWith("..") || isAbsolute(rel)) {
    return arg;
  }
  return `./${rel.split(sep).join("/")}`;
}

export function renderManagedBlock(input: {
  projectRoot: string;
  tool: string;
  hookMode: HookMode;
  serverDefinition: McpServerDefinition;
  skills: SkillSelection[];
}): string {
  // Relative to the project root, never absolute. The MCP config needs an
  // absolute path (a client's cwd when spawning a server is not guaranteed)
  // and is gitignored, so a machine-specific path there is harmless. This
  // block is written into CLAUDE.md / AGENTS.md / GEMINI.md, which are
  // committed — an absolute path here lands in everyone else's checkout
  // pointing at a directory that exists on exactly one machine.
  const command = [
    input.serverDefinition.command,
    ...(input.serverDefinition.args ?? []).map((arg) => portablePath(arg, input.projectRoot)),
  ].join(" ");
  return [
    MARKERS.begin,
    "Generated by xtctx setup. Do not edit inside this block.",
    "",
    "# xtctx Handoff",
    "",
    `Tool: ${input.tool}`,
    // Stripped, not raw: a path containing the end marker (legal on POSIX)
    // would terminate the block early, leaving its tail as debris in the
    // user's file plus a stale marker that breaks every later run.
    `Project root: ${stripMarkers(input.projectRoot)}`,
    `Integration mode: ${input.hookMode}`,
    "",
    "xtctx is configured for cross-tool handoff in this project.",
    "Do not rely on this block for a generated summary; raw local transcripts are authoritative.",
    "",
    "## Session Retrieval",
    "- Call `xtctx_recent_sessions` to list recent local sessions.",
    "- Call `xtctx_session_detail` with a `session_ref` for the raw transcript messages.",
    "- Call `xtctx_search_sessions` only when you need semantic or keyword search across chronological transcript windows.",
    "- Use `xtctx_continuity_status` for wiring and freshness diagnostics.",
    "- External orchestrators can call `xtctx_handoff_manifest` for stable session references and raw-detail pointers; it does not persist task state.",
    "",
    ...renderSyncedSkillsBlock(input.skills),
    "## MCP",
    `- Command: \`${command}\``,
    "- Transport: stdio",
    "",
    "## Notes",
    "- Indexing is on-demand from MCP recent, detail, and search calls.",
    "- There is no xtctx daemon, API server, dashboard, durable memory, or generated brief.",
    "- Content outside this managed block is preserved.",
    MARKERS.end,
    "",
  ].join("\n");
}

export async function upsertManagedBlock(
  filePath: string,
  block: string,
  containWithin: string,
  prelude = "",
): Promise<boolean> {
  const existing = await readUtf8IfExists(filePath);
  // Deliberately not trimmed. Trimming the tail here silently edited the
  // user's file: blank lines at EOF vanished, and two trailing spaces on the
  // last line — a markdown hard break — were destroyed. The separator below is
  // exactly what removal takes back, so the round trip is byte-for-byte.
  const repaired = existing ? removeManagedBlocks(existing) : "";
  // A file that already opens with YAML frontmatter keeps it — prepending
  // the prelude again would produce a second, invalid frontmatter block.
  const hasFrontmatter = repaired.startsWith("---");
  const prefix =
    prelude && !hasFrontmatter && !repaired.startsWith(prelude.trimEnd()) ? prelude : "";
  const separator = repaired.length > 0 ? "\n\n" : "";
  const content = `${prefix}${repaired}${separator}${block}`;
  return writeIfChanged(filePath, content, containWithin);
}

export async function inspectManagedFile(filePath: string): Promise<{
  exists: boolean;
  blockCount: number;
  staleReferences: string[];
}> {
  const content = await readUtf8IfExists(filePath);
  if (content === null) {
    return { exists: false, blockCount: 0, staleReferences: [] };
  }

  return {
    exists: true,
    blockCount: countManagedBlocks(content),
    staleReferences: findStaleReferences(content),
  };
}

function findStaleReferences(content: string): string[] {
  const stale: Array<{ label: string; pattern: RegExp }> = [
    { label: "xtctx serve", pattern: /\bxtctx\s+serve\b/ },
    { label: "xtctx_search", pattern: /\bxtctx_search\b/ },
    { label: "xtctx_project_knowledge", pattern: /\bxtctx_project_knowledge\b/ },
    { label: "xtctx_save_decision", pattern: /\bxtctx_save_decision\b/ },
    { label: "xtctx_save_error_solution", pattern: /\bxtctx_save_error_solution\b/ },
    { label: "xtctx_save_faq", pattern: /\bxtctx_save_faq\b/ },
    { label: "xtctx_last_session_brief", pattern: /\bxtctx_last_session_brief\b/ },
  ];
  return stale.filter((value) => value.pattern.test(content)).map((value) => value.label);
}
